
services:
  db:
    # image: postgres
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3

    # restart: always
    env_file:
      - /.env
    environment:
      MYSQL_DATABASE: ${BEND_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${BEND_DB_PASSWORD}
    #   # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
    #   # You can use whatever password you like
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #   # Password for root access
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3309:3306
      # - 5432:5432
    volumes:
      - my-db:/var/lib/mysql
      # - my-db:/var/lib/postgresql/data
    networks:
      - app-network
  api:
    image: school_api
    build: ./  #aquí iría backend
    env_file:
      - .env
    ports: 
      - '8089:8080'
    expose:
      - '8080'
    # stdin_open: true
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

    # command: ["./wait-for-it.sh", "db:3306", "--timeout=0", "--", "./docker-entrypoint.sh"]
    #command: ["./wait-for-it.sh", "db:5432", "--timeout=0", "--", "./docker-entrypoint.sh"]
  app:
    image: bluecity_app
    tty: true
    build: ./  #aquí iría frontend
    env_file:
      - .env
    ports: 
      - '3039:3000'
    expose:
      - '3000'
    stdin_open: true
    networks:
      - app-network
    depends_on:
      - api

volumes:
  my-db:
    driver: local
networks:
  app-network:
    driver: bridge